Feature/create booking package 58
Platzi-Master-C9/booking-services pull request #119
Opened 2022-03-18 23:42 UTC by artiko00

Hi! we were added jest eslint and prettier! best regards! have a nice weekend!

2022-03-19 23:42 UTC, artiko00 commented
#58

2022-03-30 23:27 UTC, elyager requested changes
There more changes required, see this [example](https://github.com/Platzi-Master-C9/booking-services/pull/117/files)

2022-04-01 21:07 UTC, artiko00 commented
@elyager Hi! can you check the PR again? thanks!

2022-04-10 17:49 UTC, JoseNoriegaa commented on packages/admin-panel/.gitignore
> +coverage
Can you add EOL here?

2022-04-10 17:51 UTC, JoseNoriegaa commented on packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js
> +}
Can you add EOF here?

2022-04-10 17:51 UTC, JoseNoriegaa commented on packages/api-gateway/src/drivers/http/adapters/booking/handlers.js
> +}
EOF

2022-04-10 17:52 UTC, JoseNoriegaa commented on packages/api-gateway/src/drivers/http/routes/admin_panel/api/index.js
> +module.exports = adminPanelRouter;
EOF

2022-04-10 17:53 UTC, JoseNoriegaa commented on packages/booking/src/index.js
> +console.log("Booking squad")
EOF

2022-04-10 18:08 UTC, JoseNoriegaa commented on packages/booking/package.json
> +    "test": "echo \"Error: run tests from root\" && exit 1"
I noticed that you added the jest.config file, but you don't added the "test" command to run the tests.

2022-04-10 18:10 UTC, JoseNoriegaa requested changes
I noticed that this PR is outdated, so please, rebase this PR, and make sure you run `yarn lint:fix` inside the api-gateway package and fix the eslint issues that may appear.

2022-04-14 15:49 UTC, gojideth commented
Hi! I changed the requested changes to be able to merge this PR. #58

2022-04-14 18:24 UTC, JoseNoriegaa commented on packages/api-gateway/src/drivers/http/adapters/index.js
> +  bookingAdapters,
Looks like you removed accidentally the geolocationAdapters from the exported modules, Can you added again?
```suggestion
  bookingAdapters,
  geolocationAdapters,
```

2022-04-14 18:32 UTC, JoseNoriegaa commented on packages/api-gateway/src/drivers/http/adapters/index.js
> +const bookingAdapters = require('./booking/handlers');
Missing reference to messageAdapters
```suggestion
const bookingAdapters = require('./booking/handlers');
const messageAdapters = require('./messages/handlers');
```

2022-04-14 18:36 UTC, JoseNoriegaa requested changes
There are a couple of details in the api-gateway, probably due to merge commits, I recommend you use rebase instead of merge so you don't ended up with a lot of commits in you PR because right now your PR is a bit difficult to review because we don't know what you actually modified/added or what just added in merge commits.

2022-04-15 05:41 UTC, JoseNoriegaa commented on packages/booking/package.json
> +    "lib": "lib",
Can you change this to `src`?
```suggestion
    "src": "src",
```

2022-04-15 05:42 UTC, JoseNoriegaa commented on packages/booking/package.json
> +    "lib"
Can you change this to `src`?
```suggestion
    "src"
```

2022-04-15 05:43 UTC, JoseNoriegaa commented on packages/booking/package.json
> +  "main": "index.js",
Can you change this to `src/index.js`?
```suggestion
  "main": "src/index.js",
```

2022-04-18 21:54 UTC, gojideth commented
I changed to src instead of lib :)

2022-04-19 00:44 UTC, JoseNoriegaa approved these changes
LGTM

2022-04-19 01:26 UTC, elyager approved these changes

2022-04-19 01:56 UTC, merged