chore: Create mongoDB driver [Data monitoring] #125
Platzi-Master-C9/booking-services pull request #129
Opened 2022-03-28 17:28 UTC by YaelRmz

I create the mongoDB driver in base to requirements in this issue. I appreciate the feedback

Fix #125

2022-04-06 05:38 UTC, gh0stl1m submitted a review, later dismissed

2022-04-06 23:29 UTC, Basultobd requested changes
Two more comments :)

2022-04-06 23:29 UTC, Basultobd commented on packages/data-monitoring/config/mongodb.js
> +}
Is ths still necessary since we dont have prefixes?

2022-04-06 23:29 UTC, Basultobd commented on packages/data-monitoring/config/environment.js
> +		environment = 'DEV_'
Is this necessary since we dont have prefixes anymore?

2022-04-25 22:23 UTC, Basultobd approved these changes
LGTM!

2022-04-26 01:25 UTC, merged