Solving issue 149:
Platzi-Master-C9/booking-services pull request #153
Opened 2022-04-04 19:59 UTC by chrom13

Fixing the package name.
Issue: https://github.com/Platzi-Master-C9/booking-services/issues/149

2022-04-04 21:35 UTC, JoseNoriegaa commented on packages/notifications-system/package.json
> +  "name": "notifications-system",
Package names have to match the pattern `@booking-services/your_package_name`, so your package name should be @booking-`services/notifications-system`

2022-04-04 21:36 UTC, JoseNoriegaa commented on packages/notifications-system/README.md
> +# `message`
Can you update this file to match your package name?

2022-04-04 21:38 UTC, JoseNoriegaa requested changes
There are still many references to the messages package that should be updated to "notifications system" or something like that.

2022-04-06 01:16 UTC, Alejandrocuartas reviewed
Did you run the 'lint' script before committing?

2022-04-29 20:28 UTC, JoseNoriegaa commented
@Alejandrocuartas I think we don't need this PR anymore since this was fixed as part of another PR.

2023-11-10 15:34 UTC, closed without merging